---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:bookworm
    command: /sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
verifier:
  name: ansible
